[2025-05-31T05:36:30.037+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-31T05:36:30.046+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medallion_sales_etl.submit_medallion_sales_etl_job manual__2025-05-31T05:31:25.968605+00:00 [queued]>
[2025-05-31T05:36:30.050+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medallion_sales_etl.submit_medallion_sales_etl_job manual__2025-05-31T05:31:25.968605+00:00 [queued]>
[2025-05-31T05:36:30.050+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-05-31T05:36:30.055+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): submit_medallion_sales_etl_job> on 2025-05-31 05:31:25.968605+00:00
[2025-05-31T05:36:30.057+0000] {standard_task_runner.py:72} INFO - Started process 273 to run task
[2025-05-31T05:36:30.059+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'medallion_sales_etl', 'submit_medallion_sales_etl_job', 'manual__2025-05-31T05:31:25.968605+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/medallion_sales_etl_dag.py', '--cfg-path', '/tmp/tmpitf24q7j']
[2025-05-31T05:36:30.061+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask submit_medallion_sales_etl_job
[2025-05-31T05:36:30.094+0000] {task_command.py:467} INFO - Running <TaskInstance: medallion_sales_etl.submit_medallion_sales_etl_job manual__2025-05-31T05:31:25.968605+00:00 [running]> on host 5d1f499577a6
[2025-05-31T05:36:30.143+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='medallion_sales_etl' AIRFLOW_CTX_TASK_ID='submit_medallion_sales_etl_job' AIRFLOW_CTX_EXECUTION_DATE='2025-05-31T05:31:25.968605+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-31T05:31:25.968605+00:00'
[2025-05-31T05:36:30.144+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-31T05:36:30.161+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-05-31T05:36:30.163+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.executor.memory=2g --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --conf spark.local.dir=/opt/***/dags/spark_temp --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262 --name medallion_sales_etl_spark_job --verbose --queue root.default --deploy-mode client /opt/***/dags/medallion_etl.py
[2025-05-31T05:36:30.770+0000] {spark_submit.py:644} INFO - Using properties file: null
[2025-05-31T05:36:30.825+0000] {spark_submit.py:644} INFO - Parsed arguments:
[2025-05-31T05:36:30.826+0000] {spark_submit.py:644} INFO - master                  spark://spark-master:7077
[2025-05-31T05:36:30.826+0000] {spark_submit.py:644} INFO - remote                  null
[2025-05-31T05:36:30.826+0000] {spark_submit.py:644} INFO - deployMode              client
[2025-05-31T05:36:30.826+0000] {spark_submit.py:644} INFO - executorMemory          2g
[2025-05-31T05:36:30.827+0000] {spark_submit.py:644} INFO - executorCores           null
[2025-05-31T05:36:30.827+0000] {spark_submit.py:644} INFO - totalExecutorCores      null
[2025-05-31T05:36:30.827+0000] {spark_submit.py:644} INFO - propertiesFile          null
[2025-05-31T05:36:30.827+0000] {spark_submit.py:644} INFO - driverMemory            null
[2025-05-31T05:36:30.827+0000] {spark_submit.py:644} INFO - driverCores             null
[2025-05-31T05:36:30.828+0000] {spark_submit.py:644} INFO - driverExtraClassPath    null
[2025-05-31T05:36:30.828+0000] {spark_submit.py:644} INFO - driverExtraLibraryPath  null
[2025-05-31T05:36:30.828+0000] {spark_submit.py:644} INFO - driverExtraJavaOptions  null
[2025-05-31T05:36:30.828+0000] {spark_submit.py:644} INFO - supervise               false
[2025-05-31T05:36:30.829+0000] {spark_submit.py:644} INFO - queue                   root.default
[2025-05-31T05:36:30.829+0000] {spark_submit.py:644} INFO - numExecutors            null
[2025-05-31T05:36:30.829+0000] {spark_submit.py:644} INFO - files                   null
[2025-05-31T05:36:30.829+0000] {spark_submit.py:644} INFO - pyFiles                 null
[2025-05-31T05:36:30.829+0000] {spark_submit.py:644} INFO - archives                null
[2025-05-31T05:36:30.830+0000] {spark_submit.py:644} INFO - mainClass               null
[2025-05-31T05:36:30.830+0000] {spark_submit.py:644} INFO - primaryResource         file:/opt/***/dags/medallion_etl.py
[2025-05-31T05:36:30.830+0000] {spark_submit.py:644} INFO - name                    medallion_sales_etl_spark_job
[2025-05-31T05:36:30.830+0000] {spark_submit.py:644} INFO - childArgs               []
[2025-05-31T05:36:30.830+0000] {spark_submit.py:644} INFO - jars                    null
[2025-05-31T05:36:30.831+0000] {spark_submit.py:644} INFO - packages                org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
[2025-05-31T05:36:30.831+0000] {spark_submit.py:644} INFO - packagesExclusions      null
[2025-05-31T05:36:30.831+0000] {spark_submit.py:644} INFO - repositories            null
[2025-05-31T05:36:30.831+0000] {spark_submit.py:644} INFO - verbose                 true
[2025-05-31T05:36:30.832+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:30.832+0000] {spark_submit.py:644} INFO - Spark properties used, including those specified through
[2025-05-31T05:36:30.832+0000] {spark_submit.py:644} INFO - --conf and those from the properties file null:
[2025-05-31T05:36:30.832+0000] {spark_submit.py:644} INFO - (spark.executor.memory,2g)
[2025-05-31T05:36:30.832+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.access.key,*********(redacted))
[2025-05-31T05:36:30.833+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.endpoint,http://minio:9000)
[2025-05-31T05:36:30.833+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.impl,org.apache.hadoop.fs.s3a.S3AFileSystem)
[2025-05-31T05:36:30.833+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.path.style.access,true)
[2025-05-31T05:36:30.833+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.secret.key,*********(redacted))
[2025-05-31T05:36:30.834+0000] {spark_submit.py:644} INFO - (spark.local.dir,/opt/***/dags/spark_temp)
[2025-05-31T05:36:30.834+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:30.834+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:30.890+0000] {spark_submit.py:644} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-31T05:36:30.922+0000] {spark_submit.py:644} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-31T05:36:30.923+0000] {spark_submit.py:644} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-31T05:36:30.925+0000] {spark_submit.py:644} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-05-31T05:36:30.925+0000] {spark_submit.py:644} INFO - com.amazonaws#aws-java-sdk-bundle added as a dependency
[2025-05-31T05:36:30.926+0000] {spark_submit.py:644} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-8d92f19d-0bf8-48f3-bae2-4c7d81cb74a4;1.0
[2025-05-31T05:36:30.926+0000] {spark_submit.py:644} INFO - confs: [default]
[2025-05-31T05:36:31.006+0000] {spark_submit.py:644} INFO - found org.apache.hadoop#hadoop-aws;3.3.4 in central
[2025-05-31T05:36:31.874+0000] {spark_submit.py:644} INFO - found com.amazonaws#aws-java-sdk-bundle;1.12.262 in central
[2025-05-31T05:36:33.731+0000] {spark_submit.py:644} INFO - found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-05-31T05:36:33.911+0000] {spark_submit.py:644} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar ...
[2025-05-31T05:36:34.817+0000] {spark_submit.py:644} INFO - downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar ...
[2025-05-31T05:36:54.880+0000] {spark_submit.py:644} INFO - :: resolution report :: resolve 2812ms :: artifacts dl 21143ms
[2025-05-31T05:36:54.880+0000] {spark_submit.py:644} INFO - :: modules in use:
[2025-05-31T05:36:54.881+0000] {spark_submit.py:644} INFO - com.amazonaws#aws-java-sdk-bundle;1.12.262 from central in [default]
[2025-05-31T05:36:54.882+0000] {spark_submit.py:644} INFO - org.apache.hadoop#hadoop-aws;3.3.4 from central in [default]
[2025-05-31T05:36:54.882+0000] {spark_submit.py:644} INFO - org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2025-05-31T05:36:54.882+0000] {spark_submit.py:644} INFO - ---------------------------------------------------------------------
[2025-05-31T05:36:54.883+0000] {spark_submit.py:644} INFO - |                  |            modules            ||   artifacts   |
[2025-05-31T05:36:54.883+0000] {spark_submit.py:644} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-31T05:36:54.883+0000] {spark_submit.py:644} INFO - ---------------------------------------------------------------------
[2025-05-31T05:36:54.883+0000] {spark_submit.py:644} INFO - |      default     |   3   |   2   |   1   |   0   ||   3   |   0   |
[2025-05-31T05:36:54.884+0000] {spark_submit.py:644} INFO - ---------------------------------------------------------------------
[2025-05-31T05:36:54.884+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.884+0000] {spark_submit.py:644} INFO - :: problems summary ::
[2025-05-31T05:36:54.884+0000] {spark_submit.py:644} INFO - :::: WARNINGS
[2025-05-31T05:36:54.885+0000] {spark_submit.py:644} INFO - [FAILED     ] org.apache.hadoop#hadoop-aws;3.3.4!hadoop-aws.jar: Downloaded file size (0) doesn't match expected Content Length (962685) for https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar. Please retry. (904ms)
[2025-05-31T05:36:54.885+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.885+0000] {spark_submit.py:644} INFO - [FAILED     ] org.apache.hadoop#hadoop-aws;3.3.4!hadoop-aws.jar: Downloaded file size (0) doesn't match expected Content Length (962685) for https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar. Please retry. (904ms)
[2025-05-31T05:36:54.886+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.886+0000] {spark_submit.py:644} INFO - ==== central: tried
[2025-05-31T05:36:54.886+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.886+0000] {spark_submit.py:644} INFO - https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar
[2025-05-31T05:36:54.887+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.887+0000] {spark_submit.py:644} INFO - [FAILED     ] com.amazonaws#aws-java-sdk-bundle;1.12.262!aws-java-sdk-bundle.jar: Downloaded file size (0) doesn't match expected Content Length (280645251) for https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar. Please retry. (20234ms)
[2025-05-31T05:36:54.888+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.888+0000] {spark_submit.py:644} INFO - [FAILED     ] com.amazonaws#aws-java-sdk-bundle;1.12.262!aws-java-sdk-bundle.jar: Downloaded file size (0) doesn't match expected Content Length (280645251) for https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar. Please retry. (20234ms)
[2025-05-31T05:36:54.888+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.888+0000] {spark_submit.py:644} INFO - ==== central: tried
[2025-05-31T05:36:54.888+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.889+0000] {spark_submit.py:644} INFO - https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar
[2025-05-31T05:36:54.889+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.889+0000] {spark_submit.py:644} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-31T05:36:54.889+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.890+0000] {spark_submit.py:644} INFO - ::              FAILED DOWNLOADS            ::
[2025-05-31T05:36:54.890+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.890+0000] {spark_submit.py:644} INFO - :: ^ see resolution messages for details  ^ ::
[2025-05-31T05:36:54.891+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.891+0000] {spark_submit.py:644} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-31T05:36:54.891+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.891+0000] {spark_submit.py:644} INFO - :: org.apache.hadoop#hadoop-aws;3.3.4!hadoop-aws.jar
[2025-05-31T05:36:54.892+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.892+0000] {spark_submit.py:644} INFO - :: com.amazonaws#aws-java-sdk-bundle;1.12.262!aws-java-sdk-bundle.jar
[2025-05-31T05:36:54.892+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.892+0000] {spark_submit.py:644} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-31T05:36:54.893+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.893+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.893+0000] {spark_submit.py:644} INFO - 
[2025-05-31T05:36:54.893+0000] {spark_submit.py:644} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-05-31T05:36:54.894+0000] {spark_submit.py:644} INFO - Exception in thread "main" java.lang.RuntimeException: [download failed: org.apache.hadoop#hadoop-aws;3.3.4!hadoop-aws.jar, download failed: com.amazonaws#aws-java-sdk-bundle;1.12.262!aws-java-sdk-bundle.jar]
[2025-05-31T05:36:54.894+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1608)
[2025-05-31T05:36:54.894+0000] {spark_submit.py:644} INFO - at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-05-31T05:36:54.894+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:334)
[2025-05-31T05:36:54.895+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2025-05-31T05:36:54.895+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2025-05-31T05:36:54.895+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2025-05-31T05:36:54.895+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2025-05-31T05:36:54.895+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2025-05-31T05:36:54.896+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2025-05-31T05:36:54.896+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-05-31T05:36:54.905+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 566, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.executor.memory=2g --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --conf spark.local.dir=/opt/***/dags/spark_temp --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262 --name medallion_sales_etl_spark_job --verbose --queue root.default --deploy-mode client /opt/***/dags/medallion_etl.py. Error code is: 1.
[2025-05-31T05:36:54.907+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=medallion_sales_etl, task_id=submit_medallion_sales_etl_job, run_id=manual__2025-05-31T05:31:25.968605+00:00, execution_date=20250531T053125, start_date=20250531T053630, end_date=20250531T053654
[2025-05-31T05:36:54.996+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-31T05:36:54.997+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task submit_medallion_sales_etl_job (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.executor.memory=2g --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --conf spark.local.dir=/opt/***/dags/spark_temp --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262 --name medallion_sales_etl_spark_job --verbose --queue root.default --deploy-mode client /opt/***/dags/medallion_etl.py. Error code is: 1.; 273)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 566, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.executor.memory=2g --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --conf spark.local.dir=/opt/***/dags/spark_temp --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262 --name medallion_sales_etl_spark_job --verbose --queue root.default --deploy-mode client /opt/***/dags/medallion_etl.py. Error code is: 1.
[2025-05-31T05:36:55.006+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-31T05:36:55.017+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-31T05:36:55.019+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
