[2025-06-03T03:32:12.572+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-03T03:32:12.583+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-03T03:32:11.190874+00:00 [queued]>
[2025-06-03T03:32:12.588+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-03T03:32:11.190874+00:00 [queued]>
[2025-06-03T03:32:12.588+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-03T03:32:12.595+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ensure_datalake_bucket_exists> on 2025-06-03 03:32:11.190874+00:00
[2025-06-03T03:32:12.597+0000] {standard_task_runner.py:72} INFO - Started process 1239 to run task
[2025-06-03T03:32:12.600+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'curry_medallion_etl', 'ensure_datalake_bucket_exists', 'manual__2025-06-03T03:32:11.190874+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/medallion_sales_etl_dag.py', '--cfg-path', '/tmp/tmpzbgsxadc']
[2025-06-03T03:32:12.602+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask ensure_datalake_bucket_exists
[2025-06-03T03:32:12.636+0000] {task_command.py:467} INFO - Running <TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-03T03:32:11.190874+00:00 [running]> on host 083f94398a74
[2025-06-03T03:32:12.700+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qdinh18' AIRFLOW_CTX_DAG_ID='curry_medallion_etl' AIRFLOW_CTX_TASK_ID='ensure_datalake_bucket_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T03:32:11.190874+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-03T03:32:11.190874+00:00'
[2025-06-03T03:32:12.701+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-03T03:32:12.727+0000] {logging_mixin.py:190} INFO - Bucket 'mybucket' already exists.
[2025-06-03T03:32:12.736+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-06-03T03:32:12.752+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-03T03:32:12.753+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=curry_medallion_etl, task_id=ensure_datalake_bucket_exists, run_id=manual__2025-06-03T03:32:11.190874+00:00, execution_date=20250603T033211, start_date=20250603T033212, end_date=20250603T033212
[2025-06-03T03:32:12.787+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-03T03:32:12.804+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-03T03:32:12.805+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
