[2025-06-07T11:07:24.918+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-07T11:07:24.928+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-07T11:07:23.886346+00:00 [queued]>
[2025-06-07T11:07:24.932+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-07T11:07:23.886346+00:00 [queued]>
[2025-06-07T11:07:24.932+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-07T11:07:24.938+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ensure_datalake_bucket_exists> on 2025-06-07 11:07:23.886346+00:00
[2025-06-07T11:07:24.940+0000] {standard_task_runner.py:72} INFO - Started process 475 to run task
[2025-06-07T11:07:24.942+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'curry_medallion_etl', 'ensure_datalake_bucket_exists', 'manual__2025-06-07T11:07:23.886346+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/medallion_sales_etl_dag.py', '--cfg-path', '/tmp/tmpynyehlx5']
[2025-06-07T11:07:24.944+0000] {standard_task_runner.py:105} INFO - Job 46: Subtask ensure_datalake_bucket_exists
[2025-06-07T11:07:24.974+0000] {task_command.py:467} INFO - Running <TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-07T11:07:23.886346+00:00 [running]> on host 00aaff77bf7f
[2025-06-07T11:07:25.019+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qdinh18' AIRFLOW_CTX_DAG_ID='curry_medallion_etl' AIRFLOW_CTX_TASK_ID='ensure_datalake_bucket_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T11:07:23.886346+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T11:07:23.886346+00:00'
[2025-06-07T11:07:25.020+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-07T11:07:25.030+0000] {logging_mixin.py:190} INFO - Bucket 'mybucket' already exists.
[2025-06-07T11:07:25.030+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-06-07T11:07:25.047+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-07T11:07:25.048+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=curry_medallion_etl, task_id=ensure_datalake_bucket_exists, run_id=manual__2025-06-07T11:07:23.886346+00:00, execution_date=20250607T110723, start_date=20250607T110724, end_date=20250607T110725
[2025-06-07T11:07:25.086+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-07T11:07:25.102+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-07T11:07:25.103+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
